/** Azərbaycanın şəhər və rayonları (xidmət ərazisi seçimi üçün) */

export interface AzerbaijanLocationGroup {
  label: string;
  locations: readonly string[];
}

export const AZERBAIJAN_LOCATION_GROUPS: readonly AzerbaijanLocationGroup[] = [
  {
    label: 'Respublika şəhərləri',
    locations: [
      'Bakı',
      'Gəncə',
      'Sumqayıt',
      'Mingəçevir',
      'Naftalan',
      'Şirvan',
      'Şəki',
      'Yevlax',
      'Lənkəran',
      'Xankəndi',
      'Naxçıvan',
    ],
  },
  {
    label: 'Bakı rayonları',
    locations: [
      'Bakı, Binəqədi rayonu',
      'Bakı, Xətai rayonu',
      'Bakı, Xəzər rayonu',
      'Bakı, Qaradağ rayonu',
      'Bakı, Nərimanov rayonu',
      'Bakı, Nəsimi rayonu',
      'Bakı, Nizami rayonu',
      'Bakı, Pirallahı rayonu',
      'Bakı, Sabunçu rayonu',
      'Bakı, Suraxanı rayonu',
      'Bakı, Səbail rayonu',
      'Bakı, Yasamal rayonu',
    ],
  },
  {
    label: 'Rayonlar',
    locations: [
      'Abşeron',
      'Ağcabədi',
      'Ağdam',
      'Ağdaş',
      'Ağstafa',
      'Ağsu',
      'Astara',
      'Balakən',
      'Bərdə',
      'Beyləqan',
      'Biləsuvar',
      'Cəbrayıl',
      'Cəlilabad',
      'Daşkəsən',
      'Füzuli',
      'Gədəbəy',
      'Goranboy',
      'Göyçay',
      'Göygöl',
      'Hacıqabul',
      'İmişli',
      'İsmayıllı',
      'Kəlbəcər',
      'Kürdəmir',
      'Laçın',
      'Lerik',
      'Masallı',
      'Neftçala',
      'Oğuz',
      'Qax',
      'Qazax',
      'Qəbələ',
      'Qobustan',
      'Quba',
      'Qubadlı',
      'Qusar',
      'Saatlı',
      'Sabirabad',
      'Salyan',
      'Samux',
      'Siyəzən',
      'Şabran',
      'Şamaxı',
      'Şəmkir',
      'Şuşa',
      'Tərtər',
      'Tovuz',
      'Ucar',
      'Xaçmaz',
      'Xızı',
      'Xocalı',
      'Xocavənd',
      'Yardımlı',
      'Zaqatala',
      'Zəngilan',
      'Zərdab',
    ],
  },
  {
    label: 'Naxçıvan MR',
    locations: [
      'Babək',
      'Culfa',
      'Kəngərli',
      'Ordubad',
      'Sədərək',
      'Şahbuz',
      'Şərur',
    ],
  },
] as const;

/** Bütün ünvan dəyərlərinin düz siyahısı */
export const AZERBAIJAN_LOCATIONS: readonly string[] =
  AZERBAIJAN_LOCATION_GROUPS.flatMap((group) => [...group.locations]);
